# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87d6dbbbf98ba223c5212440464fbd6ed9e382b62aac9d0399c79a50a4addbfa27a3b3d841888ad0d0e7d17ecfd32579b5bfdcf64c777024a7fb8b1e624e9f21
  auth0_app_id: XIQM4mA5zvubxvrijjV2yDGhqqc9DGSB
  auth0_app_secret: T4dgEMeBifGQwndLJ_sf7uUnnzPugJOq9Kw7wtsS4EEJXwvbDhD2l8Sd98oop06U
  auth0_app_endpoint: quiz-master.eu.auth0.com
  redis_url: redis://localhost:6379
  app_url: http://localhost:3000

test:
  secret_key_base: 7679bc4b574bfcf6bb4a8b91f48efbfe45460bba1f737c3897cb4b4387c5b010a1e9e47a4612424416c68748ca59595193fc5e1832b398dbd9b707fe2358413a
  app_url: http://test.host
  auth0_app_endpoint: auth0.test.com

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  database_url: <%= ENV['DATABASE_URL'] %>
  redis_url: <%= ENV['REDIS_URL'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  auth0_app_id: <%= ENV['AUTH0_APP_ID'] %>
  auth0_app_secret: <%= ENV['AUTH0_APP_SECRET'] %>
  auth0_app_endpoint: <%= ENV['AUTH0_APP_ENDPOINT'] %>
  app_url: <%= ENV['APP_URL'] %>
